name: Release and Split

on:
  release:
    types: [published]

jobs:
  split:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [view, routing, http, framework, database, controller, console, config, exception, middleware]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Split ${{ matrix.package }}
        uses: symplify/monorepo-split-github-action@main
        env:
          PAT: ${{ secrets.GH_PAT }}
        with:
          package_directory: '${{ matrix.package }}'
          repository_organization: 'abdullahadeeel'
          repository_name: '${{ matrix.package }}'
          branch: 'master'
          user_name: 'phpify-bot'
          user_email: 'bot@phpify.io'
